### ISSUE TITLE
Implementation on GPU

### ISSUE THREAD

**Issue by glenbhermon** [PySimpleGUI/PySimpleGUI-YOLO#4]
Hello! 
Please tell me how to run this on GPU. I'm not able to configure GPU access. This code doesn't run on GPU (runs on CPU with low frame-rate). Thanks in advance.

**Comment by PySimpleGUI** [comment]
Hi there!  Glad you're finding the code helpful and understand the desire to run using hardware acceleration.  I've no idea how to make this happen and it's well beyond the scope of the PySimpleGUI project.  There should be quite a bit of information on the net about how to use a GPU to accelerate the OpenCV library.'

This StackOverflow link from a couple of years ago has a good start.

https://stackoverflow.com/questions/63601580/use-gpu-with-opencv-python

It's clear that at least at that time you need to compile the opencv library from source in order to get GPU acceleration.
